### ISSUE TITLE
Error parsing commandline option lua: option not found

### ISSUE THREAD

**Issue by oemmerson** [kevmitch/mpv-autocrop#1]
Hi, I get the below error message on the current stable version of Ubuntu (14.04).

```
STDOUT/STDERR was
Error parsing commandline option lua: option not found

Exiting... (Fatal error)'
```

Does this mean the version of mpv that Ubuntu installs wasn't compiled with lua scripting support?
I have tried installing lua5.1 and then lua5.2 but get the same error message.

Thanks

**Comment by kevmitch** [comment]
Yes, Ubuntu refuses to fix their [packaging error](https://bugs.launchpad.net/ubuntu/+source/mpv/+bug/1252159) for 6 months now. I guess their LTS policy is to leave it broken or something dumb even though it's just a one line fix that doesn't even touch the source. 

You can either build from [source](https://github.com/mpv-player/mpv-build/), or use [this ppa](https://launchpad.net/~mc3man/+archive/ubuntu/mpv-tests).

**Comment by oemmerson** [comment]
Hi, Sorry for not responding for so long. For some reason I didn't get a notification from Github.
I'll try building from source and see how I get on.
Thanks
